version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npm install && nmp build && npm start"
    ports:
      - 3005:3000
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    networks:
      - nginx-proxy
    restart: always

networks:
  nginx-proxy:
    external: true
